version: 2

sources:
  - name: northwind_erp 
  - schema: northwind_EL
    tables:
      - name: public_categories
      - name: public_customers
      - name: public_employee_territories
      - name: public_employees
      - name: public_order_details
      - name: public_orders
      - name: public_products
      - name: public_region
      - name: public_shippers
      - name: public_suppliers
      - name: public_territories
      - name: public_us_states


